var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var webUtil={},gcom={callbackFuncList:{},MESSAGE_IDX:1,DEBUG_MODE:!0,comXmlPath:"/cm/xml",MAIN_TAB_ID:"win_main",BASE_URL:location.protocol+"//"+location.host,authorization:"",loginInfo:{userId:"",userNm:""},header:{type:"",message:"",action:""},body:{},fileBaseDir:"C:/MyProjectSP4/RESOURCE/upload/up",fileExt:"doc, docx, ppt, pptx, xls, xlsx, pdf, txt, text, hwp, png, jpeg, gif, jpg, tif, bmp, zip, csv, xml",maxUploadSize:104857600,_cmCodeInfo:{lnkCodeNm:"lnkCode_",grpCdNm:"clasCd",cmCd:"dtlCd",cmNm:"dtlCdNm"},
_pageInfo:{pageHeight:0,gridHeight:0,grpBtnTop:0,grpBtnHeight:0,remainHeight:0},labelList:{},msgList:{}};webUtil.getServerDate=function(a){comUtil.isNull(a)&&(a="yyyyMMdd");return WebSquare.date.getCurrentServerDate(a)};webUtil.getLocalTimeStamp=function(){return WebSquare.date.toTimestampString(new Date)};webUtil.getAddDate=function(a,b){var c=comUtil.getNumberOnly(a);return 8!=c.length?a:WebSquare.date.dateAdd(c,b)};
webUtil.getWeek=function(a){var b=comUtil.getNumberOnly(a);return 8!=b.length?a:WebSquare.date.getDay(b)};webUtil.getLunar=function(a){var b=comUtil.getNumberOnly(a);return 8!=b.length?a:WebSquare.date.toLunar(b)};
webUtil.diffDate=function(a,b){var c=a,d=b,e="",g="";if(0==c.length&&0==d.length)return 0;if(8>c.length||8>d.length)return-1;8<=c.length&&(c=a.substring(0,8),e=a.substring(8));8<=d.length&&(d=b.substring(0,8),g=b.substring(8));a=WebSquare.date.dateDiff(c,d);return 0<e.length&&0<g.length&&0==a&&parseInt(e)>parseInt(g)?-1:a};webUtil.getStringByte=function(a){return WebSquare.util.getStringByteSize(a)};
webUtil.setNumber=function(a){"number"==typeof a&&(a=""+a);if(comUtil.isNull(a))return"";a=webUtil.getNumber(a.trim());return WebSquare.util.setNumber(a)};webUtil.getNumber=function(a){return WebSquare.util.getNumber(a.trim())};webUtil.initPageInfo=function(a){return{curPage:1,recPerPage:a||10,totCount:0}};webUtil.setPageInfo=function(a,b,c){var d=parseInt(b/c.recPerPage);0!=b%c.recPerPage&&d++;a.setCount(d)};
webUtil.getBrowserCheck=function(){return WebSquare.util.isIEAllVersion()?"IE":WebSquare.util.isFF()?"FF":WebSquare.util.isChrome()?"CR":WebSquare.util.isSafari()?"SA":WebSquare.util.isOpera()?"OP":""};webUtil.isMobile=function(){return WebSquare.util.isMobile()};webUtil._isIphone=function(){return-1!=navigator.userAgent.indexOf("iPhone")||-1!=navigator.userAgent.indexOf("iPod")||-1!=navigator.userAgent.indexOf("iPad")?!0:!1};
webUtil._isAndroid=function(){return-1!=navigator.userAgent.indexOf("Android")?!0:!1};
webUtil.setEnterKeyEvent=function(a,b,c){a="string"==typeof a?$p.getComponentById(a):a;a=WebSquare.util.getChildren(a,{excludePlugin:"group trigger textbox output calendar image span",recursive:!0});try{for(var d=0;d<a.length;d++)try{"function"===typeof b&&a[d].bind("onkeyup",function(a){if(13===a.keyCode&&"function"===typeof this.getRef){var d=this.getRef().substring(5).split(".");if("undefined"!==typeof d&&2===d.length){a=d[1];var d=$p.getComponentById(d[0]),e=d.getObjectType().toLowerCase();"datamap"===
e?d.set(a,this.getValue()):"datalist"===e&&"undefined"!==typeof c&&d.setCellData(c,a,this.getValue())}b()}})}catch(e){$p.log("### webUtil.setEnterKeyEvent Exception \x3d\x3d\x3e "+e.message)}finally{dataCollection=null}}catch(e){$p.log("### webUtil.setEnterKeyEvent Exception \x3d\x3d\x3e "+e.message)}finally{a=null}};
webUtil.getXMLFileName=function(){var a="",b=$p.getParameter("w2xPath");comUtil.isNull(b)||(a=b.substring(b.lastIndexOf("/")+1,b.lastIndexOf(".")));if(-1==a.indexOf("index")||-1==a.indexOf("login"))b=$p.top().win_main.getSelectedWindowId(),b=$p.top().dlt_AllMenu.getMatchedJSON("menuId",b,!0),1==b.length&&(a=b[0].menuUrl,a=a.substring(a.lastIndexOf("/")+1,a.lastIndexOf(".")));return a};
webUtil.addBlockEvent=function(){function a(a,b,e){window.addEventListener?a.addEventListener(b,e,!1):window.attachEvent&&a.attachEvent("on"+b,e)}function b(a){window.event&&(window.event.cancelBubble=!0,window.event.returnValue=!1);a&&a.stopPropagation&&a.preventDefault&&(a.stopPropagation(),a.preventDefault())}a(document,"selectstart",b);a(document,"contextmenu",b);document.body&&"undefined"!=document.body.style.MozUserSelect&&(document.body.style.MozUserSelect="none")};
webUtil.textEncode=function(a){return a.replace(/&/g,"\x26amp;amp;").replace(/</g,"\x26amp;lt;").replace(/>/g,"\x26amp;gt;").replace(/ /g,"\x26nbsp;").replace(/\t/g,"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;").replace(/\r\n/g,"\x3cbr /\x3e").replace(/\n/g,"\x3cbr /\x3e").replace(/\r/g,"\x3cbr /\x3e")};webUtil.getObjectType=function(a){var b=typeof a;return"object"!==b?b:a.constructor==={}.constructor?"json":a.constructor===[].constructor?"array":"null"};
webUtil.getObject=function(a,b){b=b||"";if("parent"==b)b=$p.parent().$p;else if("top"==b)b=$p.top().$p;else if(""==b)b=$p;else{var c;if(c=-1<b.indexOf("mf_")?WebSquare.util.getComponentById(b):WebSquare.util.getComponentById("mf_"+b))b=c.getWindow().$p}a=a||"";var d;try{d=""!=a&&b.id&&0==b.id.indexOf("mf")?"scwin"==a?$w.getComponentById(b.getRuntimeId("scwin")):b.getComponentById(a):""!=a&&0==a.id.indexOf("mf")?WebSquare.util.getComponentById(a):$p.getComponentById(a)}catch(e){}return d};
webUtil.checkFileExt=function(a){var b=gcom.fileExt.replaceAll(" ","").split(",");if(-1<a.lastIndexOf("."))for(var c=0;c<b.length;c++)if(-1!=a.toLowerCase().indexOf(b[c]))return!0;return!1};webUtil.getFileExtCheck=function(a,b){b=b||"FILE_NAME";a="string"==typeof a?$p.getComponentById(a):a;a=webUtil.getDataListObject(a);if(null==a)return webUtil.showAlert(_error_msg.DEV_NO_DATALIST),!1;for(var c=0;c<a.getTotalRow();c++){var d=a.getCellData(c,b);if(!webUtil.checkFileExt(d.trim()))return!1}return!0};
webUtil._errorResult=function(a,b,c,d){var e=a.colInfo.length;a.isValid=!1;a.colInfo[e]={};a.colInfo[e].colId=b;a.colInfo[e].msg=c;a.colInfo[e].value=d};
webUtil.inputValidCheckJSON=function(a){for(var b={isValid:!0,colInfo:[]},c="",d="",e="",g="",h=0;h<a.length;h++){var f=a[h],k=f.type||"",m=(f.mandatory||"n").toLowerCase(),l=f.display||"",t=(f.alphabet||"n").toLowerCase(),v=(f.upper||"n").toLowerCase(),u=(f.lower||"n").toLowerCase(),x=(f.numeric||"n").toLowerCase(),A=(f.hangul||"n").toLowerCase(),y=f.other||"",z=parseInt(f.minLength)||0,D=parseInt(f.maxLength)||0,C=(f.zero||"y").toLowerCase(),w=parseInt(f.digit)||0,B=(f.trim||"y").toLowerCase(),
q=f.ltrim||"",E=f.rtrim||"",r="",n="",p=$p.getComponentById(f.id);if(comUtil.isNull(p))webUtil._errorResult(b,f.id,_error_msg.DEV_COM_ID_NONE,"");else if(r=p.getID(),f=p.getPluginName(),comUtil.isNull(f))webUtil._errorResult(b,r,_error_msg.DEV_COM_ERR,"");else{if("editor"==f)n=p.getHTML();else if("body"==f)continue;else n=p.getValue();"number"==typeof n&&(n=""+n);"y"==B?n=n.trim():("y"==q&&(n=n.ltrim()),"y"==E&&(n=n.rtrim()));"number"!=typeof n&&"editor"!=f&&p.setValue(n);""==l&&(l=r.substring($p.id.length),
p=l.indexOf("_"),l=$p.getComponentById($p.id+"tbx_"+l.substring(p+1)),l=comUtil.isNull(l)?r:l.getValue());p=l.split("\x3cspan\x3e*\x3c/span\x3e");2==p.length&&(l=p[1]);l="["+l+"] ";if("y"==m&&0==n.length)webUtil._errorResult(b,r,l+_error_msg.ERR_IN_MAND_ITEM,n);else{"n"==x&&("y"==C||0<w)&&(C="n",w=0);m=n.indexOf(".");p=n;f=!1;if("y"==x&&"n"==t&&"n"==A&&"n"==v&&"n"==u){if(0<n.length&&!comUtil.isNumeric(n,!0)){webUtil._errorResult(b,r,l+_error_msg.ERR_IN_NUM_RIGHT,n);continue}f=!0}-1<m&&f&&(p=n.substring(0,
m));if(0<z&&0<p.length&&p.length<minlength)f?webUtil._errorResult(b,r,l+comUtil.getDynamicMessage(_error_msg.ERR_IN_NUM_MIN,z),n):webUtil._errorResult(b,r,l+comUtil.getDynamicMessage(_error_msg.ERR_IN_MIN,z),n);else if(0<D&&p.length>D)f?webUtil._errorResult(b,r,l+comUtil.getDynamicMessage(_error_msg.ERR_IN_NUM_MAX,D),n):webUtil._errorResult(b,r,l+comUtil.getDynamicMessage(_error_msg.ERR_IN_MAX,D),n);else if("y"==x&&"n"==C&&0==parseInt(n,10))webUtil._errorResult(b,r,l+_error_msg.ERR_IN_UP_ZERO,n);
else{if("y"==x&&0<w&&-1<m&&(p=n.substring(m+1,n.length),-1==y.indexOf(".")&&(y+="."),p.length>w)){webUtil._errorResult(b,r,l+comUtil.getDynamicMessage(_error_msg.ERR_IN_DIGIT_LEN,w),n);continue}z=!0;"DATE"==k&&0<n.length?z=comUtil.checkValidDate(n):"EMAIL"==k&&0<n.length?z=comUtil.checkMail(n):"TEL_NO"==k&&0<n.length?(c+=n,9<=c.length&&(z=comUtil.checkTelNo(c),c=""),e=r):"REG_NO"==k&&0<n.length&&(d+=n,13<=d.length&&(z=comUtil.regCheck(d),d=""),g=r);if(z){k="";"y"==t?k+="alphabet;upper;lower;":("y"==
v&&(k+="upper;"),"y"==u&&(k+="lower;"));"y"==x&&(k+="numeric;");"y"==A&&(k+="hangul;");0<y.length&&(k+="other\x3d"+y+";");if(0<k.length&&0<n.length&&(t=comUtil.checkValidForInput(k,n,l,r),"OK"!=t)){if(t==_error_msg.ERR_UNKNOWN)return webUtil.showAlert(t),!1;webUtil._errorResult(b,r,t,n)}if(p=$p.getComponentById(r))f=p.getPluginName().toLowerCase(),"inputcalendar"==f||"calendar"==f?p.removeClass("redBorder"):p.removeClass("inRedBorder")}else webUtil._errorResult(b,r,l+_error_msg.ERR_IN_RIGHT,n)}}}}0<
c.length&&((z=comUtil.checkTelNo(c))||webUtil._errorResult(b,e,"전화번호 "+_error_msg.ERR_IN_RIGHT,c));0<d.length&&((z=comUtil.regCheck(d))||webUtil._errorResult(b,g,"주민등록번호 "+_error_msg.ERR_IN_RIGHT,d));if(!b.isValid){a="";for(c=0;c<b.colInfo.length;c++)if(d=b.colInfo[c],0<c&&(a+="\n"),l=d.colId.split($p.id),a+=d.msg,p=$p.getComponentById(d.colId))f=p.getPluginName().toLowerCase(),"inputcalendar"==f||"calendar"==f?p.addClass("redBorder"):p.addClass("inRedBorder");webUtil.showAlert(a,function(){webUtil.inputValidCheckJSONCallback(b.colInfo[0].colId)})}return b.isValid};
webUtil.inputValidCheckJSONCallback=function(a){"undefined"!=typeof a&&(a=$p.getComponentById(a))&&a.focus()};webUtil._getI18NUrl=function(){var a=WebSquare.cookie.getCookie("locale");return null==a||""==a?"/websquare/engine/servlet/I18N.jsp?locale\x3dko\x26w2xPath\x3d":"/websquare/engine/servlet/I18N.jsp?locale\x3d"+unescape(a)+"\x26w2xPath\x3d"};webUtil.isNull=function(a){return"number"==typeof a?!1:"undefined"==typeof a||null==a||""==a||"null"==a?!0:!1};
webUtil.toClipBoardPaste=function(a){"undefined"!=typeof a&&(a.select(),document.execCommand("copy"))};webUtil.wframePostScript=function(){console.log(" webUtil.wframePostScript ")};webUtil.divideTelNo=function(a,b){a=comUtil.divideTelNo(a);(b=$p.getComponentById(telOpt.no1))&&b.setValue(a.no1);(b=$p.getComponentById(telOpt.no2))&&b.setValue(a.no2);(b=$p.getComponentById(telOpt.no3))&&b.setValue(a.no3)};
webUtil.reloadPage=function(){if(0<$p.top().win_main.currentWindowNum){var a=$p.top().win_main.getSelectedWindowId();setTimeout(function(a){$p.top().win_main.getFrame(a).reload()},100,a)}};webUtil.paramToJSON=function(){for(var a=location.href,a=a.substring(a.indexOf("?")+1).split("\x26"),b={},c=1;c<a.length;c++){var d=a[c].split("\x3d");b[d[0]]=d[1]}return b};webUtil.showClose=function(a){webUtil._showMessagePopup("close",a)};
webUtil.showAlert=function(a,b,c){webUtil._showMessagePopup("alert",a,b,c)};webUtil.showConfirm=function(a,b,c){webUtil._showMessagePopup("confirm",a,b,c)};webUtil.errorMessagePopup=function(a,b){webUtil.openCommonPopup({id:"errorMsgPopup",type:"wframePopup",title:"서버에러",url:gcom.comXmlPath+"/errorMsgPop.xml",className:"type3",width:500,height:320,resizable:!1,useMaximize:!1,popupParam:{type:"json",userCallBack:b||"",name:"popInfo",data:{detail:{message:a}}}})};
webUtil._showMessagePopup=function(a,b,c,d){var e={};"undefined"!=typeof d&&d.btnList&&(e={confirm:d.btnList.confirm?d.btnList.confirm:"확인",cancel:d.btnList.cancel?d.btnList.cancel:"취소",close:d.btnList.close?d.btnList.close:"닫기"});a={type:"json",name:"popInfo",data:{detail:{type:a,message:b},button:e,param:"undefined"!=typeof d&&d.param?d.param:{},isClose:!0},title:"undefined"!=typeof d&&d.title?d.title:"알림창",width:500,height:320,param:"undefined"!=typeof d&&d.param?d.param:""};webUtil.openCommonPopup({id:"_commonMessagePopup_",
type:"wframePopup",title:a.title,url:gcom.comXmlPath+"/messagePop.xml",className:"type3",width:a.width,height:a.height,resizable:!1,useMaximize:!1,popupParam:a},c)};webUtil.errorPopupResize=function(a,b,c){eval(a).setSize(b,c)};
webUtil.openCommonPopup=function(a,b){if(comUtil.isNull(a))comUtil.errorMessageDisplay("### webUtil.openCommonPopup: popOpt is not found");else{var c="string"==typeof a?JSON.parse(a):a,d=c.id||"",e=c.type||"wframePopup",g=c.title||" ";a=c.url;var h=c.width||400,f=c.height||400,k=c.top||-1,m=c.left||-1,l="undefined"==typeof c.modal||1==c.modal?!0:!1,t="browserPopup"!=e?!0:!1;if(null==a)comUtil.errorMessageDisplay("### webUtil.openCommonPopup: url is not found");else{"undefined"==typeof c.popupParam&&
(c.popupParam={});"undefined"==typeof c.popupParam.data&&(c.popupParam.data={});c.popupParam.data.id=d;c.popupParam.data.type="json";c.popupParam.data.mode="wframePopup"==e?"W":"iframePopup"==e?"I":"B";c.popupParam.data.frameId=$p.id;if("function"==typeof b)if("wframePopup"==e){var v="__close_callback_Func__"+comUtil.getLocalDateTime("YYYYMMddhhmmssn");gcom.callbackFuncList[$p.id+v]=b;c.popupParam.data.objCallBackNm=$p.id+v}else{alert("inline(object) callback함수는 popup type이 wframePopup만 지원합니다.\n그 외는 string으로 사용하십시오.");
return}else"undefined"!=typeof b&&""!=b?c.popupParam.data.userCallBack="wframePopup"==e?$p.id+(b||""):"iframePopup"==e?$p.id+(b||""):b||"":webUtil.isNull(c.popupParam.userCallBack)||(c.popupParam.data.userCallBack="wframePopup"==e?$p.id+(c.popupParam.userCallBack||""):"iframePopup"==e?$p.id+(c.popupParam.userCallBack||""):c.popupParam.userCallBack||"");c.popupParam.type||(c.popupParam.type="json");b=c.popupParam;var v=void 0!=window.screenLeft?window.screenLeft:screen.left,u=void 0!=window.screenTop?
window.screenTop:screen.top,x=window.innerWidth?window.innerWidth:document.documentElement.clientWidth?document.documentElement.clientWidth:screen.width,A=window.innerHeight?window.innerHeight:document.documentElement.clientHeight?document.documentElement.clientHeight:screen.height;t?(m=0<m?m+(window.pageXOffset||document.body.scrollLeft):x/2-h/2+(window.pageXOffset||document.body.scrollLeft),k=0<k?k+(window.pageYOffset||document.body.scrollTop):A/2-f/2+(window.pageYOffset||document.body.scrollTop)):
(m=0<m?m+v:x/2-h/2+v,k=0<k?k+u:A/2-f/2+u);!0===c.fixedTop&&(k=c.top,m=c.left);c={id:d,type:e,width:h+"px",height:f+"px",top:k,left:m,className:c.className||"",popupName:g,modal:l,useIFrame:t,dataObject:b,alwaysOnTop:c.alwaysOnTop||!1,useModalStack:0==c.useModalStack?!1:!0,resizable:0==c.resizable?!1:!0,useMaximize:0==c.useMaximize?!1:!0};"undefined"!==typeof c.popupUrl&&-1<c.popupUrl.indexOf("w2xPath")?$p.openPopup(null,c):$p.openPopup(a,c)}}};webUtil.closeAction=function(a,b){return!0};
webUtil.closePopup=function(a,b){comUtil.isNull(scwin.popInfo)?alert("팝업정보 없음: scwin.popInfo \x3d $p.getParameter('popInfo');"):("undefined"==typeof scwin.popInfo.detail&&(scwin.popInfo.detail={}),"undefined"==typeof scwin.popInfo.isClose&&(scwin.popInfo.isClose=!0),scwin.popInfo.isClose&&("B"==scwin.popInfo.mode?window.close():$p.closePopup(a)),a=b||"",""!=a&&(a="string"!=typeof a?JSON.stringify(b):b),b=scwin.popInfo.objCallBackNm,"undefined"!=typeof b&&-1<b.indexOf("__close_callback_Func__")?((0,gcom.callbackFuncList[b])(a),
delete gcom.callbackFuncList[b]):null!=scwin.popInfo.userCallBack&&scwin.popInfo.userCallBack!=$p.id&&0<scwin.popInfo.userCallBack.length&&scwin.popInfo.userCallBack.length!=scwin.popInfo.frameId.length&&("B"==scwin.popInfo.mode?(b=opener.eval(scwin.popInfo.frameId+scwin.popInfo.userCallBack),b(a)):"I"==scwin.popInfo.mode?(b=parent.eval(scwin.popInfo.userCallBack),b(a)):(b=eval(scwin.popInfo.userCallBack),"function"==typeof b&&b(a))))};
webUtil.getPopupId=function(){return $p.getPopupId()?$p.getPopupId():window.scwin.$w.getPopupId()};
webUtil.tabOpen=function(a){var b=a.mode||"NEW",c=comUtil.isNull(a.srcPath)?"":a.srcPath,d=a.title||"",e=a.menuId||d,g=a.openAction||"selectWindow",h=$p.top().win_main.currentWindowNum;0==c.length?webUtil.showAlert(_error_msg.COM_URL_NOT_FOUND):0<h?(h=$p.top().win_main.getSelectedWindowId(),comUtil.isNull(h)||(a={menuId:e,menuNm:d,pgmUrl:c,param:a.param},e=$p.top().win_main.getWindowByWindowId(e),"NEW"==b?"undefined"!=typeof e&&null!=e&&(g="existWindow"):"REPLACE"==b&&$p.top().win_main.closeWindow(),
$p.top().scwin.executeScreen(a,g))):(a={menuId:e,menuNm:d,pgmUrl:c,param:a.param},$p.top().scwin.executeScreen(a,"existWindow"))};webUtil.getSelectedWindowFrame=function(a){var b=a.getSelectedWindowId();return a.getWindowByWindowId(b)};
webUtil.getOrgPageSize=function(a,b){gcom._pageInfo.pageHeight=document.body.clientHeight;gcom._pageInfo.gridHeight=a[0].getStyle("height").replace("px","");comUtil.isNull(b)||(gcom._pageInfo.grpBtnTop=b.getPosition("top"),gcom._pageInfo.grpBtnHeight=b.getSize("height"));gcom._pageInfo.remainHeight=gcom._pageInfo.pageHeight-(gcom._pageInfo.grpBtnTop+gcom._pageInfo.grpBtnHeight)};
webUtil.gridHeightEvent=function(a){for(var b=gcom._pageInfo.pageHeight-document.body.clientHeight,c=0;c<a.length;c++){var d=gcom._pageInfo.gridHeight-b;30<gcom._pageInfo.remainHeight?d+=gcom._pageInfo.remainHeight-30:(d-=30,gcom._pageInfo.remainHeight=30);100>d&&(d=100);d+="px";a[c].setStyle("height",d)}};webUtil.setNavigatorMenu=function(a,b,c){var d=[];webUtil.searchUpperMenu(a,b,d);d.reverse();for(a=0;a<d.length;a++)if(b=$p.getComponentById(c+(a+1)))b.show(""),b.setValue(d[a].menuNm)};
webUtil.searchUpperMenu=function(a,b,c){a=a.getMatchedJSON("menuId",b,!0);1==a.length&&(c.push(a[0]),webUtil.searchUpperMenu(a[0].parentId))};webUtil.createDynamicDataList=function(a){comUtil.isNull(a.type)&&(a.type="dataList");webUtil.createDynamicDataCollection(a)};
webUtil.createDynamicDataCollection=function(a){var b=$p.getComponentById(a.id),c="undefined"==typeof a.remove||1==a.remove?!0:!1;!comUtil.isNull(b)&&c&&$p.data.remove(a.id);b={id:a.id,type:a.type};b.option="dataMap"==a.type?{baseNode:"map"}:{baseNode:"list",repeatNode:"map",saveRemovedData:"true"};for(var c=[],d=0;d<a.info.length;d++){var e={},g=a.info[d];e.id=g.id;e.name="undefined"!=typeof g.name?g.name:g.id;e.dataType="undefined"!=typeof g.dataType?g.dataType:"text";c.push(e)}"dataMap"==a.type?
b.keyInfo=c:b.columnInfo=c;$p.data.create(b)};webUtil.copyDataList=function(a,b){var c=[];a=("string"==typeof a?$p.getComponentById(a):a).getInfo().columnInfo;for(var d in a){var e={},g;for(g in a[d])e[g]=a[d][g];c.push(e)}webUtil.createDynamicDataList({id:b,type:"dataList",info:c})};
webUtil._createCommonCodeMap=function(){var a=$p.getComponentById("dma_commonCode");comUtil.isNull(a)||$p.data.remove("dma_commonCode");comUtil.isNull(a)&&$p.data.create({id:"dma_commonCode",type:"dataMap",option:{baseNode:"map"},keyInfo:[{id:gcom._cmCodeInfo.grpCdNm,name:"그룹코드",dataType:"text"},{id:"DATA_PREFIX",name:"dlt_CommonCode",dataType:"text"}]})};
webUtil._createCommonCodeDataList=function(a){var b=$p.getComponentById(a);comUtil.isNull(b)||$p.data.remove(a);comUtil.isNull(b)&&$p.data.create({id:a,type:"dataList",option:{baseNode:"list",repeatNode:"map",saveRemovedData:"true"},columnInfo:[{id:gcom._cmCodeInfo.grpCdNm,name:"그룹코드",dataType:"text"},{id:gcom._cmCodeInfo.cmCd,name:"공통코드",dataType:"text"},{id:gcom._cmCodeInfo.cmNm,name:"공통코드명",dataType:"text"}]})};
webUtil.getCommonCodeList=function(a,b,c){c="";var d=[];webUtil._createCommonCodeMap();webUtil._createCommonCodeDataList("dlt_CommonCode");for(var e=0;e<a.length;e++){var g=a[e].code.trim();0<e&&(c+=",");c+=g;d.push("dlt_CommonCode_"+g);webUtil._createCommonCodeDataList(d[e])}dma_commonCode.set(gcom._cmCodeInfo.grpCdNm,c);dma_commonCode.set("DATA_PREFIX","dlt_CommonCode");webUtil.callSubmitJson({id:"submitCommonCodeList",ref:'data:json, { id: "dma_commonCode", key: "queryData", action: "" }',target:'data:json, { id: "dlt_CommonCode", key: "body.inqCommCodeList" }',
action:"/portal/com/commCode/inqCommCodeList",codeCallBack:"webUtil._getCommonCodeListCallback",userCallBack:b||""},a)};webUtil._getCommonCodeListCallback=function(a,b,c){webUtil.setCodeObject(b);"function"===typeof c?eval(c)(a,b):$p.log("### _getCommonCodeListCallback: "+c+" \x3d\x3d\x3e function 이 없습니다.")};
webUtil.setCodeObject=function(a){for(var b=0;b<a.length;b++){var c=a[b],d="dlt_CommonCode_"+c.code,e=$p.getComponentById(d);if(e){var g=dlt_CommonCode.getMatchedJSON(gcom._cmCodeInfo.grpCdNm,c.code,!0);0<g.length&&e.setJSON(g);g=c.object;if(!comUtil.isNull(g))for(var g=g.split(","),h=c.removeCode,f=0;f<g.length;f++){var k=g[f].split(":"),m;(m=1==k.length?$p.getComponentById(g[f].trim()):$p.getComponentById(k[0].trim()))?(comUtil.isNull(h)||webUtil._removeCommonCode(e,h),1==k.length?m.setNodeSet("data:"+
d,gcom._cmCodeInfo.cmNm,gcom._cmCodeInfo.cmCd):m.setColumnNodeSet(k[1].trim(),"data:"+d,gcom._cmCodeInfo.cmNm,gcom._cmCodeInfo.cmCd)):$p.log("### webUtil.setCodeObject \x3d\x3d\x3e "+c.object+" not found (grid or selectbox)")}}else $p.log("### webUtil.setCodeObject \x3d\x3d\x3e "+d+" not found (dataList)")}};webUtil._removeCommonCode=function(a,b){b=b.split(",");for(var c=0;c<b.length;c++){var d=a.getMatchedIndex(gcom._cmCodeInfo.cmCd,b[c].trim(),!0);0<d.length&&a.removeRows(d)}};
webUtil.getDataCollectionId=function(a){a=$p.getComponentById(a);if(!comUtil.isNull(a)&&"function"==typeof a.getRef&&(a=a.getRef().trim(),""!=a&&(a=a.substring(5).split("."),"undefined"!=typeof a&&2==a.length))){var b={};b.dataMapId=a[0];b.columnId=a[1];return b}return null};
webUtil.initGroup=function(a,b){a="object"==typeof a?a:$p.getComponentById(a);webUtil._initGroupOnly(a);if("undefined"!=typeof b)if("string"==typeof b)alert('그리드 리스트는 string의 array 현태로 넘겨야 합니다\n(ex) initGroup(group1, ["gridView1", "gridView2"])');else for(a=0;a<b.length;a++){var c=$p.getComponentById(b[a]);c?c.initGrid():$p.log("### webUtil._initGroup \x3d\x3d\x3e "+b[a]+" not found")}};
webUtil._initGroupOnly=function(){for(var a=0;a<arguments.length;a++){var b=arguments[a].getChildren(),c;for(c in b){var d=b[c];if("object"!=typeof d.getPluginName()){var e=d.getPluginName().toLowerCase();comUtil.isNull(e)?$p.log("### initGroup: "+d.getID()+" is null"):"input"==e?comUtil.isNull(d.defaultValue)?d.setValue(""):d.setValue(d.defaultValue):"inputcalendar"==e||"calendar"==e||"multiselect"==e||"autocomplete"==e||"secret"==e||"searchbox"==e||"textarea"==e||"checkbox"==e?d.setValue(""):"selectbox"==
e?"true"==d.allOption+""?d.setValue("all"):d.setValue(""):"radio"==e?d.reset():"group"==e?webUtil._initGroupOnly(d):"editor"==e&&d.setHTML("")}}}};webUtil.getDataListObject=function(a){var b="string"==typeof a?$p.getComponentById(a):a;a=b.getDataList();if(""!==a)if(b=$p.getComponentById(a),comUtil.isNull(b))$p.log("DataList("+a+")를 찾을 수 없습니다.");else return b;else $p.log(b.getID()+"는 DataList가 셋팅되어 있지 않습니다.");return null};
webUtil.gridExcelDownload=function(a,b,c){a="string"==typeof a?$p.getComponentById(a):a;var d=a.dataList;c=comUtil.isNull(c)?[]:c;if(0==d.getTotalRow())webUtil.showAlert(_error_msg.COM_EXCEL_DOWN);else{d={type:"1",startRowIndex:0,startColumnIndex:0,hiddenColumn:!1,fileName:comUtil.getLocalDateTime("YYYYMMDD_hhmm")+".xlsx",autoSizeColumn:!0,useFooter:!0,useSubTotal:!0,useSubTotalData:!0,groupby:"true",columnMove:"true",maxRowCount:b.maxRowCount||1E3,colMerge:"true",colMergeValue:"true",useStyle:!0,
showProcess:!0};b=$.extend({},d,b);null!=c&&0<c.length&&(b.startRowIndex=c[c.length-1].rowIndex+2);var e="",g=0;comUtil.isNull(b.removeColumns)||(e=b.removeColumns,g++);if(!b.hiddenColumn)for(d=0;d<a.getTotalCol();d++)a.getColumnVisible(d)||(0<g&&(e+=","),e+=d,g++);b.removeColumns=e;if(b.useProvider){g=[];e=e.split(",");for(d=0;d<a.getTotalCol();d++)if(0<e.length){for(var h=!1,f=0;f<e.length;f++)if(d==parseInt(e[f].trim())){h=!0;break}h||g.push(a.getColumnID(d))}else g.push(a.getColumnID(d));d=WebSquare.xml.parse(b.providerRequestXml,
!1);WebSquare.xml.setValue(d,"data/keyMap",g.join(","));b.providerRequestXml=WebSquare.xml.serialize(d);$p.log("### options.providerRequestXml \x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3e\n"+b.providerRequestXml)}a.advancedExcelDownload(b,c)}};
webUtil.multiDownloadExcel=function(a,b){if(comUtil.isNull(a))return alert("option은 필수 입력입니다."),!1;for(var c=a.excelInfo,d=0,e=0;e<c.length;e++){var g=$p.getComponentById(c[e].gridId);if(null==g)return alert("그리드가 없습니다: "+c[e].gridId),!1;var h=g.dataList;if(0==h.getTotalRow())return alert("엑셀로 다운로드할 데이터가 없습니다."),!1;d+=h.getTotalRow();c[e].sheetName=c[e].sheetName||"sheet"+(e+1);c[e].type=c[e].type||"1";c[e].startRowIndex=c[e].startRowIndex||(!0===a.multipleSheet?0:2);c[e].startColumnIndex=c[e].startColumnIndex||
0;c[e].rowsByN=h.getTotalRow();var f="",k=0;"undefined"!=typeof c[e].removeColumns&&""!=c[e].removeColumns&&(f=c[e].removeColumns,k++);for(var m=0;m<h.getTotalCol();m++)g.getColumnVisible(m)||(0<k&&(f+=","),f+=m,k++);c[e].removeColumns=f;null!=infoArr&&0<infoArr.length&&(c[e].startRowIndex=infoArr[infoArr.length-1].rowIndex+2);c[e].infoArr=infoArr}d=comUtil.getLocalDateTime("YYYYMMDD_hhmm")+".xlsx";$p.multipleExcelDownload({common:{fileName:b||d,showProcess:!0,multipleSheet:!0===a.multipleSheet?"true":
"false"},excelInfo:c})};webUtil.gridExcelUpload=function(a,b){a="string"===typeof a?$p.getComponentById(a):a;comUtil.isNull(a)?comUtil.errorMessageDisplay("[Grid] "+_error_msg.DEV_GRIDID_NONE):(b=$.extend({},{type:"1",headerExist:"1",startRowIndex:2,startColumnIndex:0,sheetNo:0,append:"0",hidden:"0"},b),a.advancedExcelUpload(b))};
webUtil.deleteGridView=function(a){var b=$p.getComponentById(a.gridId);if(comUtil.isNull(b))webUtil.showAlert("grid not found \x3d\x3d\x3e "+a.gridId);else{var c=b.dataList,d=comUtil.isNull(a.chkColId)?"chk":a.chkColId,d=b.getCheckedIndex(d);0==d.length&&(b=b.getFocusedRowIndex(),0<=b&&d.push(b));if(0<d.length){for(b=d.length-1;-1<b;b--)"C"==c.getRowStatus(d[b])?c.removeRow(d[b]):c.deleteRow(d[b]);"undefined"!=typeof a.userCallBack&&eval(a.userCallBack)(a.param)}else webUtil.showAlert(_error_msg.COM_DEL_SELECT_Q)}};
webUtil.removeCancelGridView=function(a,b){try{var c="string"===typeof a?$p.getComponentById(a):a,d=comUtil.isNull(b)?"chk":b,e=c.dataList;if(null===e)comUtil.errorMessageDisplay(_error_msg.DEV_NO_DATALIST);else{for(var g=c.getCheckedIndex(d),h=g.length-1;0<=h;h--){var f=g[h];e.undeleteRow(f);"Y"==e.getCellData(f,d)?e.setCellData(f,d,"N"):c.setCellChecked(f,d,!1)}if(0==c.getCheckedIndex(d).length){var k=c._getMatchedHeaderId(d);c.setHeaderValue(k,!0);c.setHeaderValue(k,!1)}}}catch(m){$p.log("[webUtil.removeCancleGridView] Exception :: "+
m.message)}};webUtil.getGridViewModify=function(a){for(var b=0;b<a.length;b++){var c=$p.getComponentById(a[b]);if(c)if(c=$p.getComponentById(c.getDataList())){if(0==c.getModifiedJSON({DB:!0}).length)return webUtil.showAlert(_error_msg.COM_NO_CHANGE),!1}else $p.log("### Grid: "+a[b]+"에 bind된 dataList를 찾을 수 없습니다.")}return!0};
webUtil.setDateGridData=function(a,b,c){var d="string"==typeof a?$p.getComponentById(a):a;if(null!=d)if("undefined"==typeof b||"string"==typeof b)alert('컬럼ID가 없습니다.\n또는 컬럼ID는 string의 array형태로 해야 합니다\nex)webUtil.setDateGridData("moduleListForm", ["insDtm", "modDtm"])');else{for(a=0;a<d.getTotalRow();a++)for(var e=0;e<b.length;e++){var g=d.getCellData(a,b[e]),g=comUtil.numberToStringDate(g);"undefined"!=typeof c&&null!=c[e]&&5<c[e].length&&(g=g.substring(0,c[e].length));d.setCellData(a,b[e],g)}d.reform()}else $p.log("### webUtil.setDateGridData: "+
a+" not found")};
webUtil.gridValidCheckJSON=function(a,b){if(comUtil.isNull(a))return comUtil.errorMessageDisplay("[Grid] "+_error_msg.DEV_GROUP_NAME),!1;a="string"==typeof a?$p.getComponentById(a):a;var c=webUtil.getDataListObject(a);if(null==c)return comUtil.errorMessageDisplay(_error_msg.DEV_NO_DATALIST),!1;for(var d=c.getModifiedIndex(),e=0;e<d.length;e++){var g=d[e],h=c.getRowStatus(g);if("C"==h||"U"==h||"1"==h||"2"==h)for(h=0;h<b.length;h++){var f=b[h].hid||"",k=b[h].cid||"",m=(b[h].mandatory||"n").toLowerCase(),
l=(b[h].alphabet||"n").toLowerCase(),t=(b[h].upper||"n").toLowerCase(),v=(b[h].lower||"n").toLowerCase(),u=(b[h].numeric||"n").toLowerCase(),x=(b[h].hangul||"n").toLowerCase(),A=b[h].other||"",y=parseInt(b[h].minlength)||0,z=parseInt(b[h].maxlength)||0,D=(b[h].zero||"y").toLowerCase(),C=parseInt(b[h].digit)||0,w=b[h].type||"";if(" "==b[h].cid.charAt(0)||" "==b[h].cid.charAt(b[h].cid.length-1))return alert("잘못된 그리드컬럼ID(ID에 space가 포함됨: ["+b[h].cid+"]"),!1;var B=a.getReadOnly("column",g,k);if("undefined"==
typeof a.getHeaderValue(f))f="";else{var q=a.getHeaderValue(f).split("* ");1==q.length?f="["+a.getHeaderValue(f)+"] ":(f=q[1].split("\x3c/span\x3e"),f=1==f.length?"["+q[1]+"] ":"["+f[0]+"] ")}q=""+c.getCellData(g,k);q=q.trim();if("y"==m&&0==q.length)return webUtil.showAlert(f+_error_msg.ERR_IN_MAND_ITEM),B||a.setFocusedCell(g,k,!0),!1;"n"==u&&(D="n",C=0);var m=q.indexOf("."),E=q,r=!1;"y"==u&&"n"==l&&"n"==t&&"n"==v&&"n"==x&&(r=!0);-1!=m&&r&&(E=q.substring(0,m));if(0<y&&E.length<y)return r?webUtil.showAlert(f+
_error_msg.ERR_IN_NUM_RIGHT+" (Min: "+y+"Byte)"):webUtil.showAlert(f+_error_msg.ERR_IN_RIGHT+" (Min: "+y+"Byte)"),B||a.setFocusedCell(g,k,!0),!1;if(0<z&&E.length>z)return r?webUtil.showAlert(f+_error_msg.ERR_IN_NUM_RIGHT+" (Max: "+z+"Byte)"):webUtil.showAlert(f+_error_msg.ERR_IN_RIGHT+" (Max: "+z+"Byte)"),B||a.setFocusedCell(g,k,!0),!1;if("y"==u&&"n"==D&&0==parseInt(q,10))return webUtil.showAlert(f+_error_msg.ERR_IN_UP_ZERO),B||a.setFocusedCell(g,k,!0),!1;if("y"==u&&0<C&&-1<m&&(E=q.substring(m+1,
q.length),-1==A.indexOf(".")&&(A+="."),E.length>C))return webUtil.showAlert(f+comUtil.getDynamicMessage(_error_msg.ERR_IN_DIGIT_LEN,C)),B||a.setFocusedCell(g,k,!0),!1;y=!0;"DATE"==w&&0<q.length?y=comUtil.checkValidDate(q):"REG_NO"==w&&0<q.length?y=comUtil.regCheck(q):"EMAIL"==w&&0<q.length&&(y=comUtil.checkMail(q));if(!y)return webUtil.showAlert(f+_error_msg.ERR_IN_RIGHT),B||a.setFocusedCell(g,k,!0),!1;w="";"y"==l?w+="alphabet;upper;lower;":("y"==t&&(w+="upper;"),"y"==v&&(w+="lower;"));"y"==u&&(w+=
"numeric;");"y"==x&&(w+="hangul;");0<A.length&&(w+="other\x3d"+A+";");if(0<w.length&&0<q.length&&(l=comUtil.checkValidForInput(w,q,f),"OK"!=l))return webUtil.showAlert(l),B||a.setFocusedCell(g,k,!0),!1}}return!0};webUtil._initPage=function(a){var b=document.body.clientHeight,c=$p.$("#"+a).offset().top,b=b-c-50;$p.$("#"+a).css("height",b)};webUtil.initGridPage=function(a){setTimeout(function(){webUti.initPage(a)},"50");window.resize=function(){webUtil._initPage(a)}};
webUtil.setGridDateTime=function(a,b){for(var c=JSON.parse(sessionStorage.userInfo).dateFormat||"yyyy-MM-dd",d=0;d<a.gridList.length;d++){var e="string"==typeof a.gridList[d].id?$p.getComponentById(a.gridList[d].id):a.gridList[d].id;if(e){for(var e=e.dataList,g=0;g<b.length;g++){var h=comUtil.getNumberOnly(b[g].regDt),f=h.substring(0,4),k=h.substring(4,6),m=h.substring(6,8);8<h.length&&h.substring(8,10);10<h.length&&h.substring(10,12);12<h.length&&h.substring(12,14);for(h=0;h<a.gridList[d].column.length;h++){var l;
l="YYYY-MM-DD"==c?f+"-"+k+"-"+m:"MM-DD-YYYY"==c?k+"-"+m+"-"+f:"DD-MM-YYYY"==c?m+"-"+k+"-"+f:f+"-"+k+"-"+m;e.insertRow();e.setCellData(g,a.gridList[d].column[h],l)}}e.modifyAllStatus("R")}else console.log("### grid not found: "+a.gridList[d].id)}};
webUtil.loginOut=function(a){gcom.loginInfo={};$p.ajax({action:"LOGIN"==a?"/test/login.do":"/test/logout.do",mode:"asynchronous",mediatype:"application/json",method:"post",processMsg:_error_msg.COM_PROC_ING,success:function(b){b=b.responseJSON;"LOGIN"==a?null!=b.sessionInfo.userId?gcom.loginInfo=b.sessionInfo:alert(_error_msg.ERR_LOGIN_FAIL):alert(_error_msg.COM_LOGOUT)},error:function(a){alert(_error_msg.ERR_OCCUR)}})};webUtil.callSubmitJson=function(a,b){webUtil._callSubmitJson(a,b)};
webUtil._callSubmitJson=function(a,b){var c=a.userCallBack||a.submitDoneHandler||"",d=a.codeCallBack||"",e="undefined"!=typeof a.errPopup&&0==a.errPopup?!1:!0,g={id:a.id||"submitTempSearchList",ref:a.ref||"",target:a.target||"",method:a.method||"post",mediatype:a.mediatype||"application/json",encoding:"UTF-8",mode:a.mode||"asynchronous",processMsg:"undefined"==typeof a.msgView||0!=a.msgView?a.processMsg||_error_msg.COM_PROC_ING:" ",action:a.action,submitHandler:function(a){},submitDoneHandler:function(f){var g,
h=f.responseJSON;g="text/plain"==a.mediatype||"text/html"==a.mediatype?"SUCCESS":"undefined"==typeof h.header?"ERROR":h.header.type;$p.getSubmission(this.id)&&$p.deleteSubmission(this.id);"SUCCESS"==g?0<d.length?eval(d)(f,b,c):0<c.length&&("string"==typeof c?eval($p.id+c)(f,b):"function"==typeof c?c(f,b):console.log("### callback 함수 없음: "+typeof c)):($p.log("\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d ERROR \x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d"),$p.log(JSON.stringify(f.responseJSON)),
$p.log("\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d"),e?(f=WebSquare.util.getPopup($p.top().$p.id+"errorMsgPopup"),$p.log("popup \x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3e "+$p.top().$p.id+"errorMsgPopup \x3d\x3d\x3e "+typeof f),f||$p.top().webUtil.errorMessagePopup(h.header.message)):"string"==typeof c?eval($p.id+c)(f,b):"function"==typeof c?c(f,b):console.log("### callback 함수 없음: "+typeof c))},
submitErrorHandler:function(a){$p.deleteSubmission(this.id);webUtil._submitError(a)}};g.processMsg=void 0==a.msgView||a.msgView?a.processMsg||_error_msg.COM_PROC_ING:a.msgView;var h=$p.getSubmission(g.id);h&&$p.deleteSubmission(g.id);$p.createSubmission(g);h=$p.getSubmission(g.id);"undefined"==typeof a.reqData?$p.executeSubmission(h):("undefined"==typeof a.viewLog||"true"!=a.viewLog&&1!=a.viewLog||$p.log("##### submission reqData \x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3e\n"+JSON.stringify(a.reqData,
null,4)),$p.executeSubmission(h,a.reqData))};webUtil._submitError=function(a){var b=a.responseBody;0<=b.indexOf("text/")&&(b=b.replace("text/",""));console.log(a);a=WebSquare.util.getPopup($p.top().$p.id+"errorMsgPopup");$p.log("popup \x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3e "+$p.top().$p.id+"errorMsgPopup \x3d\x3d\x3e "+typeof a);a||$p.top().webUtil.errorMessagePopup(b)};webUtil._callbackSubmitFunction=function(a,b){};webUtil.requestHeaderFunction=function(a){};
webUtil.reloadPage=function(){if(0<$p.top().win_main.currentWindowNum){var a=$p.top().win_main.getSelectedWindowId();setTimeout(function(a){$p.top().win_main.getFrame(a).reload()},100,a)}};webUtil.getSessionParameter=function(a,b){try{var c=sessionStorage.getItem(a);"undefined"!=typeof b&&!0!==b||sessionStorage.removeItem(a);return JSON.parse(c)}catch(d){$p.log("### "+a+" \x3d\x3e data not found: "+d.message)}return null};
webUtil.setSessionParameter=function(a,b){try{sessionStorage.setItem(a,JSON.stringify(b))}catch(c){$p.log("### setSessionParameter: "+c.message)}};webUtil.getLocalStorage=function(a,b){try{var c=localStorage.getItem(a);"undefined"!=typeof b&&!0!==b||localStorage.removeItem(a);return JSON.parse(c)}catch(d){$p.log("### "+a+" \x3d\x3e data not found: "+d.message)}return null};webUtil.setLocalStorage=function(a,b){try{localStorage.setItem(a,JSON.stringify(b))}catch(c){$p.log("### setLocalStorage: "+c.message)}};
webUtil.initPage=function(){};webUtil.getWebSquareLangCode=function(a){try{return JSON.parse(sessionStorage.userInfo).localeCd||"en"}catch(b){return console.error("[webUtil.getWebSquareLangCode] Exception :: "+b),null}};
webUtil.setWebSquareLangCode=function(a,b){try{WebSquare.cookie.setCookie("system_language",a),webUtil.getLocalStorage("langCode",a),$.getScript("/websquare/message/"+WebSquare.BootLoader.getRandomPostfix(a+".js"),function(){!0===b&&webUtil.initLabel()})}catch(c){console.error("[webUtil.setWebSquareLangCode] Exception :: "+c)}};
webUtil.initLabel=function(){try{var a=webUtil.getWebSquareLangCode();WebSquare.WebSquareLang={};for(var b=0;b<gcom.labelList.length;b++){var c=gcom.labelList[b].uiWordLocaleCd||"en",d=gcom.labelList[b].uiWordCd;c==a?WebSquare.WebSquareLang[d]=gcom.labelList[b].uiWordNm:void 0===WebSquare.WebSquareLang[d]&&"en"==c&&(WebSquare.WebSquareLang[d]=gcom.labelList[b].uiWordNm)}WebSquareLang.CheckCombobox_all="ko"==webUtil.getWebSquareLangCode()?"[일괄선택]":"[choose all]";WebSquareLang.CheckCombobox_allOption_label=
WebSquareLang.CheckCombobox_all}catch(e){console.error("[webUtil.initLabel] Exception :: "+e)}};webUtil.getMsg=function(a){try{var b=gcom.msgList.filter(function(b){return b.sysMsgId==a}),c=b.filter(function(a){return a.msgLocaleCd==webUtil.getWebSquareLangCode()})[0];if(c)return c.msgCont;var d=b.filter(function(a){return"en"==a.msgLocaleCd})[0];return d?d.msgCont:""}catch(e){return console.error("[webUtil.getMsg] Exception :: "+e),!1}};
webUtil.getMessage=function(a){try{var b="";!1===webUtil.isNull(a)&&(b=webUtil.getMsg(a));if(!1===webUtil.isNull(b)){if(1<arguments.length)for(var c=1;c<arguments.length;c++)b=-1!=b.indexOf("{"+(c-1)+"}")?webUtil.replaceAll(b,"{"+(c-1)+"}",arguments[c]):b;return b}return""}catch(d){return console.error("[webUtil.getMessage] Exception :: "+d),""}};webUtil.replaceAll=function(a,b,c){try{return a=""+a,a.split(b).join(c)}catch(d){return console.error("[webUtil.replaceAll] Exception :: "+d),a}};
webUtil.searchCommonCode=function(a,b){webUtil.createDynamicDataList({id:"dma_codeInfo",type:"dataMap",info:[{id:"dtlCd",name:"상세코드",dataType:"text"},{id:"dtlCdNm",name:"상세코드명",dataType:"text"}]});webUtil.createDynamicDataList({id:"dlt_comCode",type:"dataList",info:[{id:"clasCd",name:"그룹코드",dataType:"text"},{id:"dtlCd",name:"상세코드",dataType:"text"},{id:"dtlCdNm",name:"상세코드명",dataType:"text"}]});dma_codeInfo.set("dtlCd",a);webUtil.callSubmitJson({id:"submitsearchCommonCode",ref:'data:json, { id: "dma_codeInfo", key: "queryData", action: "" }',
target:'data:json, { id: "dlt_comCode", key: "body.inqCommCode" }',action:"/portal/com/commCode/inqCommCode",userCallBack:function(b,d){"undefined"!=typeof d&&""!=d&&"string"==typeof d&&(1==dlt_comCode.getTotalRow()?(b={code:dlt_comCode.getCellData(0,"dtlCd"),name:dlt_comCode.getCellData(0,"dtlCdNm")},eval(d)(b)):webUtil.codeSearchPopup(a,d))}},b)};
webUtil.codeSearchPopup=function(a,b){var c={type:"json",name:"popInfo",data:{detail:{key:"",allCode:[]}}};comUtil.isNull(a)||(c.data.detail.key=a,c.data.detail.allCode=dlt_comCode.getAllJSON());webUtil.openCommonPopup({id:"codeSearchPopup",title:"공통코드 조회 popup",url:"/ui/sample/popup/code_popup.xml",width:800,height:550,popupParam:c},function(a){"undefined"!=typeof a&&""!=a&&(a=JSON.parse(a),a={code:a.dtlCd,name:a.dtlCdNm},eval(b)(a))})};
webUtil.getGridColumnList=function(a){var b=[];webUtil.columnInfo=a;for(a=0;a<webUtil.columnInfo.gridInfo.length;a++)b.push(webUtil.columnInfo.gridInfo[a].id);dma_search.set("userId",webUtil.columnInfo.userId);dma_search.set("menuId",webUtil.columnInfo.menuId);dma_search.set("gridId",b);webUtil.callSubmitJson({id:"submitSearchGridInfo",ref:'data:json,{"id":"dma_search", "key":"dma_search"}',target:'data:json,{"id":"dlt_gridColListDB", "key":"body.inqGridPrsnltUI"}',action:"/portal/com/prsnlt/inqGridPrsnltUI",
submitDoneHandler:function(a,b){webUtil.getGridColumnListCallback(a)}})};
webUtil.getGridColumnListCallback=function(a){a=webUtil.columnInfo.gridInfo;for(var b=0,c=0;b<a.length;b++){var d=$p.getComponentById(a[b].id);if(d){var e=0<dlt_gridColListDB.getTotalRow()?!0:!1;webUtil.copyDataList("dlt_gridColListDB","dlt_gridColListDB_"+a[b].id);var g=$p.getComponentById("dlt_gridColListDB_"+a[b].id);lnkColList.setCondition("filter","defaultCol \x3d\x3d 'Y' \x26\x26 gridId \x3d\x3d '"+a[b].id+"'");g.setJSON(lnkColList.getAllJSON());for(var h=d.getColumnOrder(!0),f=g.getTotalRow()-
1;0<f;f--){for(var k=g.getCellData(f,"colId"),m=!1,l=0;l<h.length;l++)if(k==h[l]){m=!0;break}if(!m)for(g.removeRow(f),k=dlt_gridColListDB.getMatchedIndex("colId",k,!0),l=k.length-1;0<l;l--)a[b].id==dlt_gridColListDB.getCellData(k[l],"gridId")&&dlt_gridColListDB.removeRow(k[l])}h=d.getColumnOrder(!0);if(e){for(f=0;f<g.getTotalRow();f++)k=g.getCellData(f,"colId"),e={},e.userId=webUtil.columnInfo.userId,e.menuId=webUtil.columnInfo.menuId,e.gridId=a[b].id,e.colId=k,e.headId=d.bodyToHeaderRelation[e.colId],
e.colNm=d.getHeaderValue(e.headId),e.hideYn=1==d.getColumnVisible(d.getColumnIndex(e.colId))?"N":"Y",e.parentHeader=d.headerInfoHash[e.headId].options.parentHeader||"",e.parentHeaderValue=d.getHeaderValue(e.parentHeader),e.no=""+(f+1),k=webUtil.getSameColumnId(k,a[b].id,g),1==k.length?(e.gridSeq=k[0].gridSeq,e.defaultCol=k[0].defaultCol,e.setNm=k[0].setNm,e.devYn=k[0].devYn,e.hideYn=k[0].hideYn,"Y"==e.devYn&&(e.hideYn="Y"),g.setRowJSON(f,e,!0)):(e.gridSeq="1",e.defaultCol="Y",e.setNm="",e.devYn=e.hideYn,
g.setRowJSON(f,e,!1));for(var t,v,u,f=0;f<h.length;f++)if(e=g.getMatchedJSON("colId",h[f],!0),1==e.length){t=e[0].gridSeq;v=e[0].defaultCol;u=e[0].setNm;break}for(f=0;f<h.length;f++)e=g.getMatchedIndex("colId",h[f],!0),0==e.length&&(e={},e.userId=webUtil.columnInfo.userId,e.menuId=webUtil.columnInfo.menuId,e.gridId=a[b].id,e.colId=h[f],e.headId=d.bodyToHeaderRelation[e.colId],e.colNm=d.getHeaderValue(e.headId),e.hideYn=1==d.getColumnVisible(d.getColumnIndex(e.colId))?"N":"Y",e.parentHeader=d.headerInfoHash[e.headId].options.parentHeader||
"",e.parentHeaderValue=d.getHeaderValue(e.parentHeader),e.no=""+(f+1),e.gridSeq=t,e.defaultCol=v,e.setNm=u,e.devYn=e.hideYn,g.setRowJSON(f,e,!1))}else for(f=0;f<h.length;f++)e={},e.userId=webUtil.columnInfo.userId,e.menuId=webUtil.columnInfo.menuId,e.gridId=a[b].id,e.colId=h[f],e.headId=d.bodyToHeaderRelation[h[f]],e.colNm=d.getHeaderValue(e.headId),e.hideYn=1==d.getColumnVisible(d.getColumnIndex(h[f]))?"N":"Y",e.parentHeader=d.headerInfoHash[e.headId].options.parentHeader||"",e.parentHeaderValue=
d.getHeaderValue(e.parentHeader),e.no=""+(f+1),k=webUtil.getSameColumnId(h[f],a[b].id,g),1==k.length?(e.gridSeq=k[0].gridSeq,e.defaultCol=k[0].defaultCol,e.setNm=k[0].setNm,e.devYn=k[0].devYn,e.hideYn=k[0].hideYn,"Y"==e.devYn&&(e.hideYn="Y"),g.setRowJSON(f,e,!0)):(e.gridSeq="1",e.defaultCol="Y",e.setNm="",e.devYn=e.hideYn,g.setRowJSON(f,e,!1));webUtil.columnInfo.gridInfo[c].colList=g.getAllJSON();webUtil.redrawGridColumn(webUtil.columnInfo.gridInfo[c]);c++}}};
webUtil.getSameColumnId=function(a,b,c){a=c.getMatchedJSON("colId",a,!0);if(1<a.length){c=[];for(var d=0;d<a.length;d++)if(b==a[d].gridId){c=[a[d]];break}1==c.length&&(a=c)}return a};
webUtil.redrawGridColumn=function(a){if(!webUtil.isNull(a)){for(var b=$p.getComponentById(a.id),c=-1,d=0;d<webUtil.columnInfo.gridInfo.length;d++)if(a.id==webUtil.columnInfo.gridInfo[d].id){c=d;break}if(b){for(var e=[],g=[],d=0;d<a.colList.length;d++)e.push(a.colList[d].colId),g.push(a.colList[d].colId);e.join(",");g.join(",");b.setColumnOrder(g);g=$p.getComponentById("dlt_gridColListDB_"+a.id);if("N"==a.isDB){g.setJSON(a.colList);"Y"==a.isNew&&dlt_gridColListDB.setJSON(a.colList,!0);for(var h=dlt_gridColListDB.getMatchedIndex("gridSeq",
a.colList[0].gridSeq,!0),d=0;d<a.colList.length;d++)webUtil.columnInfo.gridInfo[c].colList[d]=a.colList[d],"Y"!=a.isNew&&dlt_gridColListDB.setRowJSON(h[d],a.colList[d],!0)}for(d=0;d<e.length;d++){c=[];if("Y"==a.isDB){if(c=webUtil.getSameColumnId(e[d],a.id,g),0==c.length){alert("error: 여기오면 안됨");break}}else for(h=0;h<a.colList.length;h++)if(e[d]==a.colList[h].colId){c=[a.colList[h]];break}1==c.length?"Y"==c[0].devYn||"Y"==c[0].hideYn?b.setColumnVisible(e[d],!1):b.setColumnVisible(e[d],!0):console.log("### webUtil.redrawGridColumn \x3d\x3e ["+
e[d]+"] not found")}}else console.log("### webUtil.redrawGridColumn \x3d\x3e ["+a.id+"] not found")}};
webUtil.setColumn=function(a,b){b=dlt_gridColListDB.getMatchedJSON("gridId",a,!0);b={menuId:webUtil.columnInfo.menuId,menuNm:webUtil.columnInfo.menuNm,allColumn:b};for(var c=$p.getComponentById("dlt_gridColListDB_"+a).getAllJSON(),d=0;d<webUtil.columnInfo.gridInfo.length&&a!=webUtil.columnInfo.gridInfo[d].id;d++);b.columnInfo=c;webUtil.openCommonPopup({id:"setGridColumnOrder",type:"browserPopup",title:"그리드컬럼설정",url:"/ui/sample/gridView/grid_private_popup.xml",width:1600,height:710,popupParam:{type:"json",
data:{scrInfo:b,userCallBack:"webUtil.setGridColumnCallback"},name:"popInfo"}})};webUtil.setGridColumnCallback=function(a){"undefined"!=typeof a&&(a=JSON.parse(a),"Y"==a.isSave?webUtil.getGridColumnList():webUtil.redrawGridColumn(a))};
webUtil.ga_pageView=function(a,b){!localStorage.getItem("cookie_agree")||"string"!==typeof b&&"object"!==typeof b||(b="string"===typeof b?JSON.parse(b):b,(b.hasOwnProperty("menuNm")||b.hasOwnProperty("pgmUrl"))&&gtag("event","page_view",{page_title:b.menuNm,page_location:a,page_path:b.pgmUrl,send_to:ga_tag}))};webUtil.userInfo=function(){return JSON.parse(sessionStorage.getItem("userInfo"))};webUtil.stringDateCheck=function(a){return moment(a,["YYYY/MM/DD","YYYY-MM-DD"],!0).isValid()};
webUtil.fullwidthToastMsg=function(a,b){toastr.options={closeButton:!1,debug:!1,newestOnTop:!1,progressBar:!1,positionClass:"toast-top-full-width",preventDuplicates:!1,onclick:null,showDuration:"300",hideDuration:"1000",timeOut:"5000",extendedTimeOut:"1000",showEasing:"swing",hideEasing:"linear",showMethod:"fadeIn",hideMethod:"fadeOut"};if("error"===a||"info"===a||"success"===a||"warning"===a)toastr[a](b)};
webUtil.toastMsg=function(a,b){toastr.options={closeButton:!1,debug:!1,newestOnTop:!1,progressBar:!1,positionClass:"toast-bottom-right",preventDuplicates:!1,onclick:null,showDuration:"300",hideDuration:"1000",timeOut:"5000",extendedTimeOut:"1000",showEasing:"swing",hideEasing:"linear",showMethod:"fadeIn",hideMethod:"fadeOut"};if("error"===a||"info"===a||"success"===a||"warning"===a)toastr[a](b)};
webUtil.isEmpty=function(a){return"object"===typeof a?0===Object.getOwnPropertyNames(a).length:"undefined"===a||"null"===a||""===a};webUtil.fileUploadPopup=function(a,b){webUtil.openCommonPopup({id:"file_upload_popup",title:"File Upload",url:"/cm/xml/fileUploadPopup.xml",width:550,height:600,popupParam:{type:"json",name:"popInfo",data:{params:a}}},b)};
webUtil.excelDownload=function(a,b){var c=$p.getFrame();$p.getComponentById("excelIframe")||$p.dynamicCreate("excelIframe","iframe",{style:"width:0; height:0; display:none",spa:"true"},c);excelIframe.setSrc(a+"?"+$.param(b.getJSON()))};
webUtil.isModified=function(a){try{var b=function(a){return"undefined"!==typeof a?0===a.getModifiedIndex().length?!1:!0:!0},c=!1;if("array"===webUtil.getObjectType(a))for(var d=$jscomp.makeIterator(a),e=d.next();!e.done;e=d.next()){var g=e.value;"object"===webUtil.getObjectType(g)&&!0===b(g)&&(c=!0)}else"object"===webUtil.getObjectType(a)&&(c=b(a));return c}catch(h){return console.error("[webUtil.isModified] Exception :: "+h),null}};
webUtil.getObjectType=function(a){try{var b=typeof a;if("object"!==b)return b;if(webUtil.isArray(a))return"array";if(webUtil.isJSON(a))return"json";if(null===a)return"null";var c=WebSquare.xml.parse("\x3cdata\x3e\x3c/data\x3e");return a.constructor===c.constructor||a.constructor===c.childNodes[0].constructor?"xml":b}catch(d){return console.error("[webUtil.getObjectType] Exception :: "+d),null}};
webUtil.isJSON=function(a){try{if(!1===jQuery.isPlainObject(a)&&!1===webUtil.isArray(a))return!1;if("object"===typeof a)try{return JSON.stringify(a),!0}catch(b){}else if("string"===typeof a)try{return JSON.parse(a),!0}catch(b){}return!1}catch(b){return console.error("webUtil.isJSON[] Exception :: "+b),!1}};
webUtil.isArray=function(a){try{return"undefined"!==typeof a&&null!==a&&"object"==typeof a&&(a.constructor.name&&"array"==a.constructor.name.toLowerCase()||a.constructor&&a.constructor==Array)?!0:!1}catch(b){return console.error("[webUtil.isArray] Exception :: "+b),!1}};
webUtil.preFormatter=function(a,b){var c;if(!b||!["YMD","YMD_HMS","YMD_HM"].includes(b)||"string"!==typeof a||8>a.length||!/^\d+$/.test(a))return a;var d=((null===(c=webUtil.userInfo())||void 0===c?void 0:c.dtFrmt)||"YYYY-MM-DD").replaceAll("-",""),e,g;c=a.length;"YMD"===b&&8===c?(e=""+d,g="YYYYMMDD"):"YMD_HMS"===b&&14===c?(e=d+"HHmmss",g="YYYYMMDDHHmmss"):"YMD_HM"===b&&12===c&&(e=d+"HHmm",g="YYYYMMDDHHmm");b=moment(a,e);return b.isValid()?b.format(g):a};
webUtil.postFormatter=function(a,b){var c;if(!b||!["YMD","YMD_HMS","YMD_HM"].includes(b)||"string"!==typeof a||8>a.length||!/^\d+$/.test(a))return a;var d=((null===(c=webUtil.userInfo())||void 0===c?void 0:c.dtFrmt)||"YYYY-MM-DD").replaceAll("-",""),e,g;c=a.length;"YMD"===b&&8===c?(e="YYYYMMDD",g=""+d):"YMD_HMS"===b&&14===c?(e="YYYYMMDDHHmmss",g=d+"HHmmss"):"YMD_HM"===b&&12===c&&(e="YYYYMMDDHHmm",g=d+"HHmm");b=moment(a,e);return b.isValid()?b.format(g):a};
webUtil.dateDisplayFormatter_YM=function(a){return"string"===typeof a&&6===a.length&&/^\d+$/.test(a)?a.substring(0,4)+"-"+a.substring(4,6):a};webUtil.dateDisplayFormatter_YMD=function(a){var b;if("string"!==typeof a||8!==a.length||!/^\d+$/.test(a))return a;var c=(null===(b=webUtil.userInfo())||void 0===b?void 0:b.dtFrmt)||"YYYY-MM-DD";b=c.replaceAll("-","");b=moment(a,b);return b.isValid()?b.format(c):a};
webUtil.dateDisplayFormatter_YMDHMS=function(a){var b;if("string"!==typeof a||14!==a.length||!/^\d+$/.test(a))return a;var c=(null===(b=webUtil.userInfo())||void 0===b?void 0:b.dtFrmt)||"YYYY-MM-DD";b=c.replaceAll("-","");b=moment(a,b+"HHmmss");return b.isValid()?b.format(c+" HH:mm:ss"):a};
webUtil.dateDisplayFormatter_YMDHM=function(a){var b;if("string"!==typeof a||12!==a.length||!/^\d+$/.test(a))return a;var c=(null===(b=webUtil.userInfo())||void 0===b?void 0:b.dtFrmt)||"YYYY-MM-DD";b=c.replaceAll("-","");b=moment(a,b+"HHmm");return b.isValid()?b.format(c+" HH:mm"):a};
webUtil.dateDisplayFormatter_DT=function(a){var b;if("string"!==typeof a||19!==a.length||!/^(\d{4})-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)$/.test(a))return a;var c=(null===(b=webUtil.userInfo())||void 0===b?void 0:b.dtFrmt)||"YYYY-MM-DD";b=moment(a,"YYYY-MM-DD HH:mm:ss");return b.isValid()?b.format(c+" HH:mm:ss"):a};webUtil.placeHolder_YMD=function(){var a;return((null===(a=webUtil.userInfo())||void 0===a?void 0:a.dtFrmt)||"YYYY-MM-DD").replaceAll("-","")};
webUtil.placeHolder_YMDHMS=function(){var a;return((null===(a=webUtil.userInfo())||void 0===a?void 0:a.dtFrmt)||"YYYY-MM-DD").replaceAll("-","")+"HHmmss"};webUtil.placeHolder_YMDHM=function(){var a;return((null===(a=webUtil.userInfo())||void 0===a?void 0:a.dtFrmt)||"YYYY-MM-DD").replaceAll("-","")+"HHmm"};
webUtil.setGridColumnPlaceHolder=function(a,b,c){"object"===typeof a&&"gridView"===(null===a||void 0===a?void 0:a.initializeType)&&"string"===typeof b&&b&&"string"===typeof c&&c&&(a=a.element.querySelector("#"+a.getID()+"_"+b),null!==a&&a.setAttribute("placeholder",c))};
webUtil.fromDBtoUI_dataList=function(a){if("dataList"===(null===a||void 0===a?void 0:a.initializeType)){var b=a.getAllJSON();Object.values(a.element.getElementsByTagName("w2:column")).filter(function(a){return a.hasAttribute("dataType")}).filter(function(a){return"text"===a.getAttribute("dataType")}).filter(function(a){return a.hasAttribute("dateFormat")}).forEach(function(a){var c=a.getAttribute("id"),e=a.getAttribute("dateFormat");b.forEach(function(a){return a[c]=webUtil.postFormatter(a[c],e)})});
b.forEach(function(b,d){return a.setRowJSON(d,b,!0)});a.modifyAllStatus("R")}};
webUtil.fromUItoDB_dataList=function(a){if("dataList"===(null===a||void 0===a?void 0:a.initializeType)){var b=a.getAllJSON();Object.values(a.element.getElementsByTagName("w2:column")).filter(function(a){return a.hasAttribute("dataType")}).filter(function(a){return"text"===a.getAttribute("dataType")}).filter(function(a){return a.hasAttribute("dateFormat")}).forEach(function(a){var c=a.getAttribute("id"),e=a.getAttribute("dateFormat");b.forEach(function(a){return a[c]=webUtil.preFormatter(a[c],e)})});
b.forEach(function(b,d){var c=a.getRowStatus(d);a.setRowJSON(d,b,!0);a.modifyRowStatus(d,c)})}};webUtil.fromUItoDB_dataMap=function(a){if("dataMap"===(null===a||void 0===a?void 0:a.initializeType)){var b=a.getInfo().keyInfo;Object.values(b).filter(function(a){return a.hasOwnProperty("dataType")}).filter(function(a){return"text"===a.dataType}).filter(function(a){return a.hasOwnProperty("dateFormat")}).forEach(function(b){var c=b.id,e=a.get(c);a.set(c,webUtil.preFormatter(e,b.dateFormat))})}};
webUtil.fromDBtoUI_dataMap=function(a){if("dataMap"===(null===a||void 0===a?void 0:a.initializeType)){var b=a.getInfo().keyInfo;Object.values(b).filter(function(a){return a.hasOwnProperty("dataType")}).filter(function(a){return"text"===a.dataType}).filter(function(a){return a.hasOwnProperty("dateFormat")}).forEach(function(b){var c=b.id,e=a.get(c);a.set(c,webUtil.postFormatter(e,b.dateFormat))})}};
webUtil.ioFormat_YMD=function(){return(webUtil.userInfo().dtFrmt||"YYYY-MM-DD").replace("YYYY","yyyy").replace("DD","dd").replaceAll("-","")};webUtil.ioFormat_YMDHM=function(){return(webUtil.userInfo().dtFrmt||"YYYY-MM-DD").replace("YYYY","yyyy").replace("DD","dd").replaceAll("-","")+"HHmm"};webUtil.ioFormat_YMDHMS=function(){return(webUtil.userInfo().dtFrmt||"YYYY-MM-DD").replace("YYYY","yyyy").replace("DD","dd").replaceAll("-","")+"HHmmSS"};
webUtil.groupBy=function(a,b){return a.reduce(function(a,d){var c=d[b];void 0===a[c]&&(a[c]=[]);a[c].push(d);return a},{})};webUtil.getParentWindow=function(){if(void 0!==parent.$p.getParentWindow().win_main){var a=parent.$p.getParentWindow().win_main.getSelectedWindowId();return parent.$p.getParentWindow().win_main.getWindow(a)}return parent.$p.getParentWindow()};
webUtil.getParentWindowTitle=function(){if(void 0!==parent.$p.getParentWindow().win_main){var a=parent.$p.getParentWindow().win_main.getSelectedWindowId();return parent.$p.getParentWindow().win_main.getWindow(a).tbx_title.options.label}return parent.$p.getParentWindow().tbx_title.options.label};
webUtil.validateGrid=function(a,b,c,d){try{var e=function(a,b,c,d,e){e=webUtil._getValResultMsg(d,e,a);if(!1===webUtil.isEmpty(e.message)){var f=k.length;k[f]={};k[f].columnId=d.id;k[f].objId=c;d.label&&!1===webUtil.isEmpty(d.label)?k[f].columnName=d.label:k[f].columnName=b.getColumnName(d.id);k[f].rowIndex=a;k[f].message="2"==e.msgType?e.message:webUtil.attachPostposition(k[f].columnName)+" "+e.message}};c=c||{};var g=c.tacObj,h=c.tabId;d=c.isCheckModified;if(null===a)return!1;var f=webUtil.getGridViewDataList(a);
if(null===f)return!1;if(!1!==d&&!webUtil.isModified(f))return webUtil.getMsg(webUtil.showAlert(webUtil.getMsg("vms.com.noAction")),null,"warning"),!1;var k=[],m=f.getModifiedIndex();for(c=0;c<m.length;c++){var l=f.getRowJSON(m[c]);if("D"!==l.rowStatus)for(var t=$jscomp.makeIterator(b),v=t.next();!v.done;v=t.next()){var u=v.value;if("undefined"!==typeof u.id&&"undefined"!==l[u.id]){var x=l[u.id];"string"===typeof x&&(x=x.trim());e(m[c],f,a.getID(),u,x)}}}if(0<k.length){if("undefined"!==typeof g&&"undefined"!==
typeof h&&""!==h){var A=g.getTabIndex(h);g.setSelectedTabIndex(A)}webUtil.showAlert(k[0].message,function(a){scwin.$w.getComponentById(k[0].objId).setFocusedCell(k[0].rowIndex,k[0].columnId,!0)},"warning");return!1}return!0}catch(y){console.error("[webUtil.validateGrid] Exception :: "+y)}};
webUtil.getGridViewDataList=function(a){try{var b=scwin,c=a.getDataList();if(""!==c){var d=b.$w.getComponentById(c);return"undefined"===typeof d||null===d?(console.log("DataList("+c+")를 찾을 수 없습니다."),null):d}console.log(a.getID()+"는 DataList가 세팅되어 있지 않습니다.");return null}catch(e){return console.error("[webUtil.getGridViewDataList] Exception :: "+e),null}};
webUtil._getValResultMsg=function(a,b,c){try{var d={msgType:"1",message:""};if("undefined"!==typeof a.mandatory&&!0===a.mandatory&&0===b.length)d.message=webUtil.getMsg("vms.com.required02");else if("undefined"!==typeof a.minLength&&0<a.minLength&&!webUtil.isEmpty(b)&&b.length<a.minLength)d.message=webUtil.getMsg("vms.com.minLength",a.minLength);else if("undefined"!==typeof a.minByteLength&&0<a.minByteLength&&!webUtil.isEmpty(b)&&scwin.getByteLength(b)<a.minByteLength)d.message=webUtil.getMsg("vms.com.minByte",
a.minByteLength);else if("undefined"!==typeof a.maxLength&&0<a.maxLength&&!webUtil.isEmpty(b)&&b.length>a.maxLength)d.message=webUtil.getMsg("vms.com.maxLength",a.maxLength);else if("undefined"!==typeof a.maxByteLength&&0<a.maxByteLength&&!webUtil.isEmpty(b)&&scwin.getByteLength(b)>a.maxByteLength)d.message=webUtil.getMsg("vms.com.maxByte",a.maxByteLength);else if("undefined"!==typeof a.allowChar&&!webUtil.isEmpty(b)&&(new RegExp("[^"+a.allowChar+"]")).test(b))d.message=webUtil.getMsg("vms.com.allowChar",
a.allowChar);else if("undefined"!==typeof a.ignoreChar&&!webUtil.isEmpty(b)&&(new RegExp("["+a.ignoreChar+"]")).test(b))d.message=webUtil.getMsg("vms.com.char01",a.ignoreChar);else if("undefined"!==typeof a.isEmail&&a.isEmail&&!1===webUtil.isEmpty(b)&&!1===scwin.isEmail(b))d.message=webUtil.getMsg("vms.com.email");else if("undefined"!==typeof a.isPhone&&a.isPhone&&!1===webUtil.isEmpty(b)&&!1===scwin.isPhone(b))d.message=webUtil.getMsg("vms.com.tel");else if("function"===typeof a.valFunc){var e=a.valFunc(b,
c);!1===webUtil.isEmpty(e)&&(d.msgType="2",d.message=e)}return d}catch(g){return console.error("[webUtil._getValResultMsg] Exception :: "+g),null}};webUtil.attachPostposition=function(a){try{return"ko"==webUtil.getWebSquareLangCode()?a=webUtil.isFinalConsonant(a)?'"'+a+'"은':'"'+a+'"는':'"'+a+'"'}catch(b){return console.error("[webUtil.attachPostposition] Exception :: "+b),a}};
webUtil.isFinalConsonant=function(a){try{var b=a.charCodeAt(a.length-1);return 44032>b||55197<b||0==(b-16)%28?!1:!0}catch(c){return console.error("[webUtil.isFinalConsonant] Exception :: "+c),null}};webUtil.setPlaceHolder_quickSrch=function(a,b){var c;a&&b&&("w2:wframe"===(null===a||void 0===a?void 0:null===(c=a.element)||void 0===c?void 0:c.tagName)||"wfm_header"===(null===a||void 0===a?void 0:a.org_id))&&"string"===typeof b&&(null===a||void 0===a?void 0:a.scope.scwin.quickSrch_setPlaceHolder(b))};
webUtil.setCombobox_quickSrch=function(a,b){var c;a&&b&&("w2:wframe"===(null===a||void 0===a?void 0:null===(c=a.element)||void 0===c?void 0:c.tagName)||"wfm_header"===(null===a||void 0===a?void 0:a.org_id))&&"object"===typeof b&&(null===a||void 0===a?void 0:a.scope.scwin.quickSrch_setCombobox(b))};imports("uiplugin.popup");